// IATA-koder → land/by. Dekker norske og franske lufthavner samt vanlige europeiske og interkontinentale knutepunkt.
// Ukjente koder kan legges til under Innstillinger.
export interface Airport {
  country: string
  city: string
}

export const AIRPORTS: Record<string, Airport> = {
  // Norge
  OSL: { country: 'NO', city: 'Oslo Gardermoen' },
  TRF: { country: 'NO', city: 'Sandefjord Torp' },
  BGO: { country: 'NO', city: 'Bergen' },
  SVG: { country: 'NO', city: 'Stavanger' },
  TRD: { country: 'NO', city: 'Trondheim' },
  TOS: { country: 'NO', city: 'Tromsø' },
  BOO: { country: 'NO', city: 'Bodø' },
  AES: { country: 'NO', city: 'Ålesund' },
  KRS: { country: 'NO', city: 'Kristiansand' },
  HAU: { country: 'NO', city: 'Haugesund' },
  MOL: { country: 'NO', city: 'Molde' },
  KSU: { country: 'NO', city: 'Kristiansund' },
  EVE: { country: 'NO', city: 'Harstad/Narvik' },
  ALF: { country: 'NO', city: 'Alta' },
  KKN: { country: 'NO', city: 'Kirkenes' },
  LKL: { country: 'NO', city: 'Lakselv' },
  BDU: { country: 'NO', city: 'Bardufoss' },
  SOG: { country: 'NO', city: 'Sogndal' },
  FDE: { country: 'NO', city: 'Førde' },
  HOV: { country: 'NO', city: 'Ørsta-Volda' },
  SDN: { country: 'NO', city: 'Sandane' },
  RRS: { country: 'NO', city: 'Røros' },
  BNN: { country: 'NO', city: 'Brønnøysund' },
  SSJ: { country: 'NO', city: 'Sandnessjøen' },
  MJF: { country: 'NO', city: 'Mosjøen' },
  MQN: { country: 'NO', city: 'Mo i Rana' },
  VDS: { country: 'NO', city: 'Vadsø' },
  HFT: { country: 'NO', city: 'Hammerfest' },
  LKN: { country: 'NO', city: 'Leknes' },
  SVJ: { country: 'NO', city: 'Svolvær' },
  ANX: { country: 'NO', city: 'Andøya' },
  SKN: { country: 'NO', city: 'Stokmarknes' },
  LYR: { country: 'NO', city: 'Longyearbyen' },
  // Frankrike
  CDG: { country: 'FR', city: 'Paris Charles de Gaulle' },
  ORY: { country: 'FR', city: 'Paris Orly' },
  BVA: { country: 'FR', city: 'Paris Beauvais' },
  NCE: { country: 'FR', city: 'Nice' },
  LYS: { country: 'FR', city: 'Lyon' },
  MRS: { country: 'FR', city: 'Marseille' },
  TLS: { country: 'FR', city: 'Toulouse' },
  BOD: { country: 'FR', city: 'Bordeaux' },
  NTE: { country: 'FR', city: 'Nantes' },
  MPL: { country: 'FR', city: 'Montpellier' },
  LIL: { country: 'FR', city: 'Lille' },
  SXB: { country: 'FR', city: 'Strasbourg' },
  BIQ: { country: 'FR', city: 'Biarritz' },
  BES: { country: 'FR', city: 'Brest' },
  RNS: { country: 'FR', city: 'Rennes' },
  TLN: { country: 'FR', city: 'Toulon' },
  PGF: { country: 'FR', city: 'Perpignan' },
  AJA: { country: 'FR', city: 'Ajaccio' },
  BIA: { country: 'FR', city: 'Bastia' },
  CLY: { country: 'FR', city: 'Calvi' },
  FSC: { country: 'FR', city: 'Figari' },
  MLH: { country: 'FR', city: 'Mulhouse/Basel' },
  EGC: { country: 'FR', city: 'Bergerac' },
  LRH: { country: 'FR', city: 'La Rochelle' },
  CFE: { country: 'FR', city: 'Clermont-Ferrand' },
  PIS: { country: 'FR', city: 'Poitiers' },
  LIG: { country: 'FR', city: 'Limoges' },
  DNR: { country: 'FR', city: 'Dinard' },
  CMF: { country: 'FR', city: 'Chambéry' },
  GNB: { country: 'FR', city: 'Grenoble' },
  // Norden
  CPH: { country: 'DK', city: 'København' },
  AAL: { country: 'DK', city: 'Aalborg' },
  BLL: { country: 'DK', city: 'Billund' },
  ARN: { country: 'SE', city: 'Stockholm Arlanda' },
  BMA: { country: 'SE', city: 'Stockholm Bromma' },
  GOT: { country: 'SE', city: 'Göteborg' },
  MMX: { country: 'SE', city: 'Malmö' },
  HEL: { country: 'FI', city: 'Helsingfors' },
  KEF: { country: 'IS', city: 'Reykjavík Keflavík' },
  // Europa
  AMS: { country: 'NL', city: 'Amsterdam' },
  BRU: { country: 'BE', city: 'Brussel' },
  FRA: { country: 'DE', city: 'Frankfurt' },
  MUC: { country: 'DE', city: 'München' },
  BER: { country: 'DE', city: 'Berlin' },
  HAM: { country: 'DE', city: 'Hamburg' },
  DUS: { country: 'DE', city: 'Düsseldorf' },
  STR: { country: 'DE', city: 'Stuttgart' },
  CGN: { country: 'DE', city: 'Köln/Bonn' },
  ZRH: { country: 'CH', city: 'Zürich' },
  GVA: { country: 'CH', city: 'Genève' },
  BSL: { country: 'CH', city: 'Basel' },
  VIE: { country: 'AT', city: 'Wien' },
  LHR: { country: 'GB', city: 'London Heathrow' },
  LGW: { country: 'GB', city: 'London Gatwick' },
  STN: { country: 'GB', city: 'London Stansted' },
  LTN: { country: 'GB', city: 'London Luton' },
  LCY: { country: 'GB', city: 'London City' },
  MAN: { country: 'GB', city: 'Manchester' },
  EDI: { country: 'GB', city: 'Edinburgh' },
  DUB: { country: 'IE', city: 'Dublin' },
  MAD: { country: 'ES', city: 'Madrid' },
  BCN: { country: 'ES', city: 'Barcelona' },
  AGP: { country: 'ES', city: 'Málaga' },
  PMI: { country: 'ES', city: 'Palma' },
  ALC: { country: 'ES', city: 'Alicante' },
  LPA: { country: 'ES', city: 'Gran Canaria' },
  TFS: { country: 'ES', city: 'Tenerife Sør' },
  LIS: { country: 'PT', city: 'Lisboa' },
  OPO: { country: 'PT', city: 'Porto' },
  FAO: { country: 'PT', city: 'Faro' },
  FCO: { country: 'IT', city: 'Roma Fiumicino' },
  MXP: { country: 'IT', city: 'Milano Malpensa' },
  LIN: { country: 'IT', city: 'Milano Linate' },
  VCE: { country: 'IT', city: 'Venezia' },
  NAP: { country: 'IT', city: 'Napoli' },
  FLR: { country: 'IT', city: 'Firenze' },
  BLQ: { country: 'IT', city: 'Bologna' },
  PRG: { country: 'CZ', city: 'Praha' },
  WAW: { country: 'PL', city: 'Warszawa' },
  KRK: { country: 'PL', city: 'Kraków' },
  GDN: { country: 'PL', city: 'Gdańsk' },
  BUD: { country: 'HU', city: 'Budapest' },
  ATH: { country: 'GR', city: 'Athen' },
  IST: { country: 'TR', city: 'Istanbul' },
  SAW: { country: 'TR', city: 'Istanbul Sabiha' },
  LUX: { country: 'LU', city: 'Luxembourg' },
  RIX: { country: 'LV', city: 'Riga' },
  TLL: { country: 'EE', city: 'Tallinn' },
  VNO: { country: 'LT', city: 'Vilnius' },
  ZAG: { country: 'HR', city: 'Zagreb' },
  SPU: { country: 'HR', city: 'Split' },
  DBV: { country: 'HR', city: 'Dubrovnik' },
  LJU: { country: 'SI', city: 'Ljubljana' },
  // Interkontinentalt
  DXB: { country: 'AE', city: 'Dubai' },
  DOH: { country: 'QA', city: 'Doha' },
  JFK: { country: 'US', city: 'New York JFK' },
  EWR: { country: 'US', city: 'Newark' },
  BOS: { country: 'US', city: 'Boston' },
  ORD: { country: 'US', city: 'Chicago' },
  MIA: { country: 'US', city: 'Miami' },
  LAX: { country: 'US', city: 'Los Angeles' },
  SFO: { country: 'US', city: 'San Francisco' },
  IAD: { country: 'US', city: 'Washington' },
  YYZ: { country: 'CA', city: 'Toronto' },
  YUL: { country: 'CA', city: 'Montréal' },
  NRT: { country: 'JP', city: 'Tokyo Narita' },
  HND: { country: 'JP', city: 'Tokyo Haneda' },
  SIN: { country: 'SG', city: 'Singapore' },
  BKK: { country: 'TH', city: 'Bangkok' },
  HKG: { country: 'HK', city: 'Hong Kong' },
  CPT: { country: 'ZA', city: 'Cape Town' },
  JNB: { country: 'ZA', city: 'Johannesburg' },
  GRU: { country: 'BR', city: 'São Paulo' },
  MEX: { country: 'MX', city: 'Mexico City' },
  SYD: { country: 'AU', city: 'Sydney' },
  CMN: { country: 'MA', city: 'Casablanca' },
  RAK: { country: 'MA', city: 'Marrakech' },
  TUN: { country: 'TN', city: 'Tunis' },
  CAI: { country: 'EG', city: 'Kairo' },
}

export const COUNTRY_NAMES: Record<string, string> = {
  NO: 'Norge',
  FR: 'Frankrike',
  DK: 'Danmark',
  SE: 'Sverige',
  FI: 'Finland',
  IS: 'Island',
  NL: 'Nederland',
  BE: 'Belgia',
  DE: 'Tyskland',
  CH: 'Sveits',
  AT: 'Østerrike',
  GB: 'Storbritannia',
  IE: 'Irland',
  ES: 'Spania',
  PT: 'Portugal',
  IT: 'Italia',
  CZ: 'Tsjekkia',
  PL: 'Polen',
  HU: 'Ungarn',
  GR: 'Hellas',
  TR: 'Tyrkia',
  LU: 'Luxembourg',
  LV: 'Latvia',
  EE: 'Estland',
  LT: 'Litauen',
  HR: 'Kroatia',
  SI: 'Slovenia',
  MC: 'Monaco',
  AE: 'De forente arabiske emirater',
  QA: 'Qatar',
  US: 'USA',
  CA: 'Canada',
  JP: 'Japan',
  SG: 'Singapore',
  TH: 'Thailand',
  HK: 'Hongkong',
  ZA: 'Sør-Afrika',
  BR: 'Brasil',
  MX: 'Mexico',
  AU: 'Australia',
  MA: 'Marokko',
  TN: 'Tunisia',
  EG: 'Egypt',
  XX: 'Annet land',
}

export const COUNTRY_CODES = Object.keys(COUNTRY_NAMES)
  .filter((c) => c !== 'XX')
  .sort((a, b) => COUNTRY_NAMES[a].localeCompare(COUNTRY_NAMES[b], 'nb'))

export function countryName(code: string): string {
  return COUNTRY_NAMES[code] ?? code
}

export function lookupAirport(code: string, custom?: Record<string, Airport>): Airport | undefined {
  const c = code.trim().toUpperCase()
  return custom?.[c] ?? AIRPORTS[c]
}

/** Vanlige flyselskapskoder (for OCR-tolkning av flightnummer). */
export const CARRIERS: Record<string, string> = {
  SK: 'SAS',
  DY: 'Norwegian',
  D8: 'Norwegian',
  DI: 'Norwegian',
  AF: 'Air France',
  KL: 'KLM',
  LH: 'Lufthansa',
  BA: 'British Airways',
  WF: 'Widerøe',
  AY: 'Finnair',
  LX: 'Swiss',
  OS: 'Austrian',
  IB: 'Iberia',
  VY: 'Vueling',
  TP: 'TAP',
  EK: 'Emirates',
  QR: 'Qatar Airways',
  TK: 'Turkish Airlines',
  FR: 'Ryanair',
  U2: 'easyJet',
  W6: 'Wizz Air',
  A3: 'Aegean',
  SN: 'Brussels Airlines',
  EW: 'Eurowings',
  HV: 'Transavia',
  TO: 'Transavia France',
  N0: 'Norse Atlantic',
  AZ: 'ITA Airways',
  EI: 'Aer Lingus',
  LO: 'LOT',
  UA: 'United',
  DL: 'Delta',
  AA: 'American',
  AC: 'Air Canada',
}
