// IATA-koder → land/by. Dekker norske og franske lufthavner samt vanlige europeiske og interkontinentale knutepunkt.
// Ukjente koder kan legges til under Innstillinger.
export interface Airport {
  country: string
  city: string
}

export const AIRPORTS: Record<string, Airport> = {
  // Norge
  OSL: { country: 'NO', city: 'Oslo Gardermoen' },
  TRF: { country: 'NO', city: 'Sandefjord Torp' },
  BGO: { country: 'NO', city: 'Bergen' },
  SVG: { country: 'NO', city: 'Stavanger' },
  TRD: { country: 'NO', city: 'Trondheim' },
  TOS: { country: 'NO', city: 'Tromsø' },
  BOO: { country: 'NO', city: 'Bodø' },
  AES: { country: 'NO', city: 'Ålesund' },
  KRS: { country: 'NO', city: 'Kristiansand' },
  HAU: { country: 'NO', city: 'Haugesund' },
  MOL: { country: 'NO', city: 'Molde' },
  KSU: { country: 'NO', city: 'Kristiansund' },
  EVE: { country: 'NO', city: 'Harstad/Narvik' },
  ALF: { country: 'NO', city: 'Alta' },
  KKN: { country: 'NO', city: 'Kirkenes' },
  LKL: { country: 'NO', city: 'Lakselv' },
  BDU: { country: 'NO', city: 'Bardufoss' },
  SOG: { country: 'NO', city: 'Sogndal' },
  FDE: { country: 'NO', city: 'Førde' },
  HOV: { country: 'NO', city: 'Ørsta-Volda' },
  SDN: { country: 'NO', city: 'Sandane' },
  RRS: { country: 'NO', city: 'Røros' },
  BNN: { country: 'NO', city: 'Brønnøysund' },
  SSJ: { country: 'NO', city: 'Sandnessjøen' },
  MJF: { country: 'NO', city: 'Mosjøen' },
  MQN: { country: 'NO', city: 'Mo i Rana' },
  VDS: { country: 'NO', city: 'Vadsø' },
  HFT: { country: 'NO', city: 'Hammerfest' },
  LKN: { country: 'NO', city: 'Leknes' },
  SVJ: { country: 'NO', city: 'Svolvær' },
  ANX: { country: 'NO', city: 'Andøya' },
  SKN: { country: 'NO', city: 'Stokmarknes' },
  LYR: { country: 'NO', city: 'Longyearbyen' },
  // Frankrike
  CDG: { country: 'FR', city: 'Paris Charles de Gaulle' },
  ORY: { country: 'FR', city: 'Paris Orly' },
  BVA: { country: 'FR', city: 'Paris Beauvais' },
  NCE: { country: 'FR', city: 'Nice' },
  LYS: { country: 'FR', city: 'Lyon' },
  MRS: { country: 'FR', city: 'Marseille' },
  TLS: { country: 'FR', city: 'Toulouse' },
  BOD: { country: 'FR', city: 'Bordeaux' },
  NTE: { country: 'FR', city: 'Nantes' },
  MPL: { country: 'FR', city: 'Montpellier' },
  LIL: { country: 'FR', city: 'Lille' },
  SXB: { country: 'FR', city: 'Strasbourg' },
  BIQ: { country: 'FR', city: 'Biarritz' },
  BES: { country: 'FR', city: 'Brest' },
  RNS: { country: 'FR', city: 'Rennes' },
  TLN: { country: 'FR', city: 'Toulon' },
  PGF: { country: 'FR', city: 'Perpignan' },
  AJA: { country: 'FR', city: 'Ajaccio' },
  BIA: { country: 'FR', city: 'Bastia' },
  CLY: { country: 'FR', city: 'Calvi' },
  FSC: { country: 'FR', city: 'Figari' },
  MLH: { country: 'FR', city: 'Mulhouse/Basel' },
  EGC: { country: 'FR', city: 'Bergerac' },
  LRH: { country: 'FR', city: 'La Rochelle' },
  CFE: { country: 'FR', city: 'Clermont-Ferrand' },
  PIS: { country: 'FR', city: 'Poitiers' },
  LIG: { country: 'FR', city: 'Limoges' },
  DNR: { country: 'FR', city: 'Dinard' },
  CMF: { country: 'FR', city: 'Chambéry' },
  GNB: { country: 'FR', city: 'Grenoble' },
  // Norden
  CPH: { country: 'DK', city: 'København' },
  AAL: { country: 'DK', city: 'Aalborg' },
  BLL: { country: 'DK', city: 'Billund' },
  ARN: { country: 'SE', city: 'Stockholm Arlanda' },
  BMA: { country: 'SE', city: 'Stockholm Bromma' },
  GOT: { country: 'SE', city: 'Göteborg' },
  MMX: { country: 'SE', city: 'Malmö' },
  HEL: { country: 'FI', city: 'Helsingfors' },
  KEF: { country: 'IS', city: 'Reykjavík Keflavík' },
  // Europa
  AMS: { country: 'NL', city: 'Amsterdam' },
  BRU: { country: 'BE', city: 'Brussel' },
  FRA: { country: 'DE', city: 'Frankfurt' },
  MUC: { country: 'DE', city: 'München' },
  BER: { country: 'DE', city: 'Berlin' },
  HAM: { country: 'DE', city: 'Hamburg' },
  DUS: { country: 'DE', city: 'Düsseldorf' },
  STR: { country: 'DE', city: 'Stuttgart' },
  CGN: { country: 'DE', city: 'Köln/Bonn' },
  ZRH: { country: 'CH', city: 'Zürich' },
  GVA: { country: 'CH', city: 'Genève' },
  BSL: { country: 'CH', city: 'Basel' },
  VIE: { country: 'AT', city: 'Wien' },
  LHR: { country: 'GB', city: 'London Heathrow' },
  LGW: { country: 'GB', city: 'London Gatwick' },
  STN: { country: 'GB', city: 'London Stansted' },
  LTN: { country: 'GB', city: 'London Luton' },
  LCY: { country: 'GB', city: 'London City' },
  MAN: { country: 'GB', city: 'Manchester' },
  EDI: { country: 'GB', city: 'Edinburgh' },
  DUB: { country: 'IE', city: 'Dublin' },
  MAD: { country: 'ES', city: 'Madrid' },
  BCN: { country: 'ES', city: 'Barcelona' },
  AGP: { country: 'ES', city: 'Málaga' },
  PMI: { country: 'ES', city: 'Palma' },
  ALC: { country: 'ES', city: 'Alicante' },
  LPA: { country: 'ES', city: 'Gran Canaria' },
  TFS: { country: 'ES', city: 'Tenerife Sør' },
  LIS: { country: 'PT', city: 'Lisboa' },
  OPO: { country: 'PT', city: 'Porto' },
  FAO: { country: 'PT', city: 'Faro' },
  FCO: { country: 'IT', city: 'Roma Fiumicino' },
  MXP: { country: 'IT', city: 'Milano Malpensa' },
  LIN: { country: 'IT', city: 'Milano Linate' },
  VCE: { country: 'IT', city: 'Venezia' },
  NAP: { country: 'IT', city: 'Napoli' },
  FLR: { country: 'IT', city: 'Firenze' },
  BLQ: { country: 'IT', city: 'Bologna' },
  PRG: { country: 'CZ', city: 'Praha' },
  WAW: { country: 'PL', city: 'Warszawa' },
  KRK: { country: 'PL', city: 'Kraków' },
  GDN: { country: 'PL', city: 'Gdańsk' },
  BUD: { country: 'HU', city: 'Budapest' },
  ATH: { country: 'GR', city: 'Athen' },
  IST: { country: 'TR', city: 'Istanbul' },
  SAW: { country: 'TR', city: 'Istanbul Sabiha' },
  LUX: { country: 'LU', city: 'Luxembourg' },
  RIX: { country: 'LV', city: 'Riga' },
  TLL: { country: 'EE', city: 'Tallinn' },
  VNO: { country: 'LT', city: 'Vilnius' },
  ZAG: { country: 'HR', city: 'Zagreb' },
  SPU: { country: 'HR', city: 'Split' },
  DBV: { country: 'HR', city: 'Dubrovnik' },
  LJU: { country: 'SI', city: 'Ljubljana' },
  // Benelux og Tyskland – sekundære
  EIN: { country: 'NL', city: 'Eindhoven' },
  RTM: { country: 'NL', city: 'Rotterdam' },
  CRL: { country: 'BE', city: 'Brussel Charleroi' },
  ANR: { country: 'BE', city: 'Antwerpen' },
  LGG: { country: 'BE', city: 'Liège' },
  BRE: { country: 'DE', city: 'Bremen' },
  HAJ: { country: 'DE', city: 'Hannover' },
  NUE: { country: 'DE', city: 'Nürnberg' },
  LEJ: { country: 'DE', city: 'Leipzig/Halle' },
  DRS: { country: 'DE', city: 'Dresden' },
  FMO: { country: 'DE', city: 'Münster/Osnabrück' },
  DTM: { country: 'DE', city: 'Dortmund' },
  FKB: { country: 'DE', city: 'Karlsruhe/Baden-Baden' },
  HHN: { country: 'DE', city: 'Frankfurt-Hahn' },
  FDH: { country: 'DE', city: 'Friedrichshafen' },
  // Norden – sekundære
  AAR: { country: 'DK', city: 'Aarhus' },
  KRP: { country: 'DK', city: 'Karup' },
  RNN: { country: 'DK', city: 'Bornholm' },
  NYO: { country: 'SE', city: 'Stockholm Skavsta' },
  VST: { country: 'SE', city: 'Stockholm Västerås' },
  LPI: { country: 'SE', city: 'Linköping' },
  NRK: { country: 'SE', city: 'Norrköping' },
  JKG: { country: 'SE', city: 'Jönköping' },
  VBY: { country: 'SE', city: 'Visby' },
  UME: { country: 'SE', city: 'Umeå' },
  LLA: { country: 'SE', city: 'Luleå' },
  KRN: { country: 'SE', city: 'Kiruna' },
  OSD: { country: 'SE', city: 'Östersund' },
  TKU: { country: 'FI', city: 'Åbo' },
  TMP: { country: 'FI', city: 'Tammerfors' },
  OUL: { country: 'FI', city: 'Uleåborg' },
  RVN: { country: 'FI', city: 'Rovaniemi' },
  VAA: { country: 'FI', city: 'Vasa' },
  AEY: { country: 'IS', city: 'Akureyri' },
  FAE: { country: 'FO', city: 'Færøyene Vágar' },
  GOH: { country: 'GL', city: 'Nuuk' },
  // Storbritannia og Irland – sekundære
  BHX: { country: 'GB', city: 'Birmingham' },
  BRS: { country: 'GB', city: 'Bristol' },
  GLA: { country: 'GB', city: 'Glasgow' },
  NCL: { country: 'GB', city: 'Newcastle' },
  LBA: { country: 'GB', city: 'Leeds Bradford' },
  LPL: { country: 'GB', city: 'Liverpool' },
  ABZ: { country: 'GB', city: 'Aberdeen' },
  INV: { country: 'GB', city: 'Inverness' },
  EMA: { country: 'GB', city: 'East Midlands' },
  SOU: { country: 'GB', city: 'Southampton' },
  BFS: { country: 'GB', city: 'Belfast' },
  CWL: { country: 'GB', city: 'Cardiff' },
  JER: { country: 'GB', city: 'Jersey' },
  GCI: { country: 'GB', city: 'Guernsey' },
  IOM: { country: 'GB', city: 'Isle of Man' },
  GIB: { country: 'GB', city: 'Gibraltar' },
  ORK: { country: 'IE', city: 'Cork' },
  SNN: { country: 'IE', city: 'Shannon' },
  // Alpene og Sentral-Europa
  BRN: { country: 'CH', city: 'Bern' },
  SZG: { country: 'AT', city: 'Salzburg' },
  INN: { country: 'AT', city: 'Innsbruck' },
  GRZ: { country: 'AT', city: 'Graz' },
  KLU: { country: 'AT', city: 'Klagenfurt' },
  LNZ: { country: 'AT', city: 'Linz' },
  BRQ: { country: 'CZ', city: 'Brno' },
  OSR: { country: 'CZ', city: 'Ostrava' },
  BTS: { country: 'SK', city: 'Bratislava' },
  KSC: { country: 'SK', city: 'Košice' },
  WRO: { country: 'PL', city: 'Wrocław' },
  POZ: { country: 'PL', city: 'Poznań' },
  KTW: { country: 'PL', city: 'Katowice' },
  WMI: { country: 'PL', city: 'Warszawa Modlin' },
  RZE: { country: 'PL', city: 'Rzeszów' },
  SZZ: { country: 'PL', city: 'Szczecin' },
  DEB: { country: 'HU', city: 'Debrecen' },
  // Frankrike – flere
  LDE: { country: 'FR', city: 'Lourdes/Tarbes' },
  PUF: { country: 'FR', city: 'Pau' },
  RDZ: { country: 'FR', city: 'Rodez' },
  BZR: { country: 'FR', city: 'Béziers' },
  NIM: { country: 'FR', city: 'Nîmes' },
  AVN: { country: 'FR', city: 'Avignon' },
  TUF: { country: 'FR', city: 'Tours' },
  UIP: { country: 'FR', city: 'Quimper' },
  LRT: { country: 'FR', city: 'Lorient' },
  CFR: { country: 'FR', city: 'Caen' },
  DOL: { country: 'FR', city: 'Deauville' },
  ETZ: { country: 'FR', city: 'Metz/Nancy' },
  DIJ: { country: 'FR', city: 'Dijon' },
  ANE: { country: 'FR', city: 'Angers' },
  XCR: { country: 'FR', city: 'Châlons-Vatry' },
  LBG: { country: 'FR', city: 'Paris Le Bourget' },
  // Italia – flere
  BGY: { country: 'IT', city: 'Milano Bergamo' },
  TRN: { country: 'IT', city: 'Torino' },
  GOA: { country: 'IT', city: 'Genova' },
  PSA: { country: 'IT', city: 'Pisa' },
  VRN: { country: 'IT', city: 'Verona' },
  TSF: { country: 'IT', city: 'Treviso' },
  TRS: { country: 'IT', city: 'Trieste' },
  BRI: { country: 'IT', city: 'Bari' },
  BDS: { country: 'IT', city: 'Brindisi' },
  CTA: { country: 'IT', city: 'Catania' },
  PMO: { country: 'IT', city: 'Palermo' },
  CAG: { country: 'IT', city: 'Cagliari' },
  OLB: { country: 'IT', city: 'Olbia' },
  AHO: { country: 'IT', city: 'Alghero' },
  CIA: { country: 'IT', city: 'Roma Ciampino' },
  AOI: { country: 'IT', city: 'Ancona' },
  PEG: { country: 'IT', city: 'Perugia' },
  // Spania og Portugal – flere
  SVQ: { country: 'ES', city: 'Sevilla' },
  VLC: { country: 'ES', city: 'Valencia' },
  BIO: { country: 'ES', city: 'Bilbao' },
  IBZ: { country: 'ES', city: 'Ibiza' },
  MAH: { country: 'ES', city: 'Menorca' },
  SCQ: { country: 'ES', city: 'Santiago de Compostela' },
  TFN: { country: 'ES', city: 'Tenerife Nord' },
  ACE: { country: 'ES', city: 'Lanzarote' },
  FUE: { country: 'ES', city: 'Fuerteventura' },
  GRX: { country: 'ES', city: 'Granada' },
  XRY: { country: 'ES', city: 'Jerez' },
  ZAZ: { country: 'ES', city: 'Zaragoza' },
  OVD: { country: 'ES', city: 'Asturias' },
  SDR: { country: 'ES', city: 'Santander' },
  GRO: { country: 'ES', city: 'Girona' },
  REU: { country: 'ES', city: 'Reus' },
  FNC: { country: 'PT', city: 'Madeira' },
  PDL: { country: 'PT', city: 'Ponta Delgada' },
  // Hellas, Kypros, Malta
  SKG: { country: 'GR', city: 'Thessaloniki' },
  HER: { country: 'GR', city: 'Heraklion' },
  CHQ: { country: 'GR', city: 'Chania' },
  RHO: { country: 'GR', city: 'Rhodos' },
  CFU: { country: 'GR', city: 'Korfu' },
  JMK: { country: 'GR', city: 'Mykonos' },
  JTR: { country: 'GR', city: 'Santorini' },
  KGS: { country: 'GR', city: 'Kos' },
  ZTH: { country: 'GR', city: 'Zakynthos' },
  LCA: { country: 'CY', city: 'Larnaca' },
  PFO: { country: 'CY', city: 'Pafos' },
  MLA: { country: 'MT', city: 'Malta' },
  // Balkan og Øst-Europa
  ZAD: { country: 'HR', city: 'Zadar' },
  PUY: { country: 'HR', city: 'Pula' },
  RJK: { country: 'HR', city: 'Rijeka' },
  TGD: { country: 'ME', city: 'Podgorica' },
  TIV: { country: 'ME', city: 'Tivat' },
  BEG: { country: 'RS', city: 'Beograd' },
  SJJ: { country: 'BA', city: 'Sarajevo' },
  SKP: { country: 'MK', city: 'Skopje' },
  TIA: { country: 'AL', city: 'Tirana' },
  PRN: { country: 'XK', city: 'Pristina' },
  OTP: { country: 'RO', city: 'București' },
  CLJ: { country: 'RO', city: 'Cluj-Napoca' },
  SOF: { country: 'BG', city: 'Sofia' },
  VAR: { country: 'BG', city: 'Varna' },
  BOJ: { country: 'BG', city: 'Burgas' },
  KUN: { country: 'LT', city: 'Kaunas' },
  PLQ: { country: 'LT', city: 'Palanga' },
  TAY: { country: 'EE', city: 'Tartu' },
  KIV: { country: 'MD', city: 'Chișinău' },
  // Tyrkia, Midtøsten, Kaukasus
  AYT: { country: 'TR', city: 'Antalya' },
  ADB: { country: 'TR', city: 'Izmir' },
  ESB: { country: 'TR', city: 'Ankara' },
  DLM: { country: 'TR', city: 'Dalaman' },
  BJV: { country: 'TR', city: 'Bodrum' },
  TLV: { country: 'IL', city: 'Tel Aviv' },
  AMM: { country: 'JO', city: 'Amman' },
  BEY: { country: 'LB', city: 'Beirut' },
  AUH: { country: 'AE', city: 'Abu Dhabi' },
  DWC: { country: 'AE', city: 'Dubai Al Maktoum' },
  MCT: { country: 'OM', city: 'Muscat' },
  BAH: { country: 'BH', city: 'Bahrain' },
  KWI: { country: 'KW', city: 'Kuwait' },
  RUH: { country: 'SA', city: 'Riyadh' },
  JED: { country: 'SA', city: 'Jeddah' },
  TBS: { country: 'GE', city: 'Tbilisi' },
  EVN: { country: 'AM', city: 'Jerevan' },
  GYD: { country: 'AZ', city: 'Baku' },
  // Afrika – flere
  HRG: { country: 'EG', city: 'Hurghada' },
  SSH: { country: 'EG', city: 'Sharm el-Sheikh' },
  AGA: { country: 'MA', city: 'Agadir' },
  FEZ: { country: 'MA', city: 'Fès' },
  TNG: { country: 'MA', city: 'Tanger' },
  DJE: { country: 'TN', city: 'Djerba' },
  ALG: { country: 'DZ', city: 'Alger' },
  DSS: { country: 'SN', city: 'Dakar' },
  ABJ: { country: 'CI', city: 'Abidjan' },
  NBO: { country: 'KE', city: 'Nairobi' },
  ADD: { country: 'ET', city: 'Addis Abeba' },
  DAR: { country: 'TZ', city: 'Dar es Salaam' },
  ZNZ: { country: 'TZ', city: 'Zanzibar' },
  MRU: { country: 'MU', city: 'Mauritius' },
  RUN: { country: 'RE', city: 'Réunion' },
  // Nord-Amerika og Asia – flere
  YVR: { country: 'CA', city: 'Vancouver' },
  YYC: { country: 'CA', city: 'Calgary' },
  ATL: { country: 'US', city: 'Atlanta' },
  DFW: { country: 'US', city: 'Dallas/Fort Worth' },
  SEA: { country: 'US', city: 'Seattle' },
  DEN: { country: 'US', city: 'Denver' },
  LAS: { country: 'US', city: 'Las Vegas' },
  MCO: { country: 'US', city: 'Orlando' },
  PHL: { country: 'US', city: 'Philadelphia' },
  DTW: { country: 'US', city: 'Detroit' },
  MSP: { country: 'US', city: 'Minneapolis' },
  HNL: { country: 'US', city: 'Honolulu' },
  ICN: { country: 'KR', city: 'Seoul Incheon' },
  KIX: { country: 'JP', city: 'Osaka Kansai' },
  PEK: { country: 'CN', city: 'Beijing' },
  PVG: { country: 'CN', city: 'Shanghai Pudong' },
  TPE: { country: 'TW', city: 'Taipei' },
  KUL: { country: 'MY', city: 'Kuala Lumpur' },
  CGK: { country: 'ID', city: 'Jakarta' },
  DPS: { country: 'ID', city: 'Bali' },
  MNL: { country: 'PH', city: 'Manila' },
  HAN: { country: 'VN', city: 'Hanoi' },
  SGN: { country: 'VN', city: 'Ho Chi Minh-byen' },
  HKT: { country: 'TH', city: 'Phuket' },
  DEL: { country: 'IN', city: 'New Delhi' },
  BOM: { country: 'IN', city: 'Mumbai' },
  CMB: { country: 'LK', city: 'Colombo' },
  MLE: { country: 'MV', city: 'Malé' },
  MEL: { country: 'AU', city: 'Melbourne' },
  BNE: { country: 'AU', city: 'Brisbane' },
  PER: { country: 'AU', city: 'Perth' },
  AKL: { country: 'NZ', city: 'Auckland' },
  // Sør- og Mellom-Amerika
  GIG: { country: 'BR', city: 'Rio de Janeiro' },
  EZE: { country: 'AR', city: 'Buenos Aires' },
  SCL: { country: 'CL', city: 'Santiago' },
  LIM: { country: 'PE', city: 'Lima' },
  BOG: { country: 'CO', city: 'Bogotá' },
  CUN: { country: 'MX', city: 'Cancún' },
  PTY: { country: 'PA', city: 'Panama City' },
  SJO: { country: 'CR', city: 'San José' },
  HAV: { country: 'CU', city: 'Havanna' },
  PUJ: { country: 'DO', city: 'Punta Cana' },
  // Interkontinentalt
  DXB: { country: 'AE', city: 'Dubai' },
  DOH: { country: 'QA', city: 'Doha' },
  JFK: { country: 'US', city: 'New York JFK' },
  EWR: { country: 'US', city: 'Newark' },
  BOS: { country: 'US', city: 'Boston' },
  ORD: { country: 'US', city: 'Chicago' },
  MIA: { country: 'US', city: 'Miami' },
  LAX: { country: 'US', city: 'Los Angeles' },
  SFO: { country: 'US', city: 'San Francisco' },
  IAD: { country: 'US', city: 'Washington' },
  YYZ: { country: 'CA', city: 'Toronto' },
  YUL: { country: 'CA', city: 'Montréal' },
  NRT: { country: 'JP', city: 'Tokyo Narita' },
  HND: { country: 'JP', city: 'Tokyo Haneda' },
  SIN: { country: 'SG', city: 'Singapore' },
  BKK: { country: 'TH', city: 'Bangkok' },
  HKG: { country: 'HK', city: 'Hong Kong' },
  CPT: { country: 'ZA', city: 'Cape Town' },
  JNB: { country: 'ZA', city: 'Johannesburg' },
  GRU: { country: 'BR', city: 'São Paulo' },
  MEX: { country: 'MX', city: 'Mexico City' },
  SYD: { country: 'AU', city: 'Sydney' },
  CMN: { country: 'MA', city: 'Casablanca' },
  RAK: { country: 'MA', city: 'Marrakech' },
  TUN: { country: 'TN', city: 'Tunis' },
  CAI: { country: 'EG', city: 'Kairo' },
}

export const COUNTRY_NAMES: Record<string, string> = {
  NO: 'Norge',
  FR: 'Frankrike',
  DK: 'Danmark',
  SE: 'Sverige',
  FI: 'Finland',
  IS: 'Island',
  NL: 'Nederland',
  BE: 'Belgia',
  DE: 'Tyskland',
  CH: 'Sveits',
  AT: 'Østerrike',
  GB: 'Storbritannia',
  IE: 'Irland',
  ES: 'Spania',
  PT: 'Portugal',
  IT: 'Italia',
  CZ: 'Tsjekkia',
  PL: 'Polen',
  HU: 'Ungarn',
  GR: 'Hellas',
  TR: 'Tyrkia',
  LU: 'Luxembourg',
  LV: 'Latvia',
  EE: 'Estland',
  LT: 'Litauen',
  HR: 'Kroatia',
  SI: 'Slovenia',
  MC: 'Monaco',
  AE: 'De forente arabiske emirater',
  QA: 'Qatar',
  US: 'USA',
  CA: 'Canada',
  JP: 'Japan',
  SG: 'Singapore',
  TH: 'Thailand',
  HK: 'Hongkong',
  ZA: 'Sør-Afrika',
  BR: 'Brasil',
  MX: 'Mexico',
  AU: 'Australia',
  MA: 'Marokko',
  TN: 'Tunisia',
  EG: 'Egypt',
  FO: 'Færøyene',
  GL: 'Grønland',
  SK: 'Slovakia',
  CY: 'Kypros',
  MT: 'Malta',
  ME: 'Montenegro',
  RS: 'Serbia',
  BA: 'Bosnia-Hercegovina',
  MK: 'Nord-Makedonia',
  AL: 'Albania',
  XK: 'Kosovo',
  RO: 'Romania',
  BG: 'Bulgaria',
  MD: 'Moldova',
  IL: 'Israel',
  JO: 'Jordan',
  LB: 'Libanon',
  OM: 'Oman',
  BH: 'Bahrain',
  KW: 'Kuwait',
  SA: 'Saudi-Arabia',
  GE: 'Georgia',
  AM: 'Armenia',
  AZ: 'Aserbajdsjan',
  DZ: 'Algerie',
  SN: 'Senegal',
  CI: 'Elfenbenskysten',
  KE: 'Kenya',
  ET: 'Etiopia',
  TZ: 'Tanzania',
  MU: 'Mauritius',
  RE: 'Réunion (Frankrike)',
  KR: 'Sør-Korea',
  CN: 'Kina',
  TW: 'Taiwan',
  MY: 'Malaysia',
  ID: 'Indonesia',
  PH: 'Filippinene',
  VN: 'Vietnam',
  IN: 'India',
  LK: 'Sri Lanka',
  MV: 'Maldivene',
  NZ: 'New Zealand',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
  CO: 'Colombia',
  PA: 'Panama',
  CR: 'Costa Rica',
  CU: 'Cuba',
  DO: 'Den dominikanske republikk',
  XX: 'Annet land',
}

export const COUNTRY_CODES = Object.keys(COUNTRY_NAMES)
  .filter((c) => c !== 'XX')
  .sort((a, b) => COUNTRY_NAMES[a].localeCompare(COUNTRY_NAMES[b], 'nb'))

export function countryName(code: string): string {
  return COUNTRY_NAMES[code] ?? code
}

export function lookupAirport(code: string, custom?: Record<string, Airport>): Airport | undefined {
  const c = code.trim().toUpperCase()
  return custom?.[c] ?? AIRPORTS[c]
}

/** Vanlige flyselskapskoder (for OCR-tolkning av flightnummer). */
export const CARRIERS: Record<string, string> = {
  SK: 'SAS',
  DY: 'Norwegian',
  D8: 'Norwegian',
  DI: 'Norwegian',
  AF: 'Air France',
  KL: 'KLM',
  LH: 'Lufthansa',
  BA: 'British Airways',
  WF: 'Widerøe',
  AY: 'Finnair',
  LX: 'Swiss',
  OS: 'Austrian',
  IB: 'Iberia',
  VY: 'Vueling',
  TP: 'TAP',
  EK: 'Emirates',
  QR: 'Qatar Airways',
  TK: 'Turkish Airlines',
  FR: 'Ryanair',
  U2: 'easyJet',
  W6: 'Wizz Air',
  A3: 'Aegean',
  SN: 'Brussels Airlines',
  EW: 'Eurowings',
  HV: 'Transavia',
  TO: 'Transavia France',
  N0: 'Norse Atlantic',
  AZ: 'ITA Airways',
  EI: 'Aer Lingus',
  LO: 'LOT',
  UA: 'United',
  DL: 'Delta',
  AA: 'American',
  AC: 'Air Canada',
}
